[workspace]
members  = ["lib", "arrow-macros/core", "arrow-macros/derive"]
resolver = "2"

[workspace.package]
edition      = "2021"
homepage     = "https://www.aetheric.nl"
license-file = "LICENSE"
repository   = "https://github.com/aetheric-oss/lib-common"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs
